//-----------------------------------------------------------------------
// <copyright file="DemoModel.cs" company="Lifeprojects.de">
//     Class: DemoModel
//     Copyright © Lifeprojects.de 2023
// </copyright>
//
// <author>Gerhard Ahrens - Lifeprojects.de</author>
// <email>developer@lifeprojects.de</email>
// <date>10.07.2023</date>
// <Template-Version>1.0</Template-Version>
//
// <summary>
// Class for
// </summary>
// <auto-generated>
//  Dieser Code wurde vom T4 Template-Generator generiert.
//
//  Änderungen an dieser Datei 'DemoModel.cs' können falsches Verhalten verursachen
//  und gehen verloren, wenn der Code erneut generiert wird. Es ist allerdings möglich zusätzliche 
//  Anpassunge in einer weiteren Klasse-Datei durch 'partial class DemoModel' durchzuführen.
// </auto-generated>
//-----------------------------------------------------------------------

namespace TemplateProject.Class
{
    using System;
    using System.Diagnostics;

    [DebuggerNonUserCode]
    [DebuggerStepThrough]
    public partial class DemoModel
    {
        public DemoModel()
        {
        }

                
                /* Fieldname: Name; Datentyp: Name; Länge: 50; Beschreibung: Vor- und Nachname*/
                public string Name { get; set; }
                
                /* Fieldname: EMail; Datentyp: EMail; Länge: 100; Beschreibung: Email-Adresse*/
                public string EMail { get; set; }
                
                /* Fieldname: ActiveDate; Datentyp: ActiveDate; Beschreibung: Aktive ab Datum*/
                public DateTime ActiveDate { get; set; }
                
                /* Fieldname: Active; Datentyp: Active; Beschreibung: Datensatz aktiv/inaktive*/
                public bool Active { get; set; }
            }
}