//-----------------------------------------------------------------------
// <copyright file="TemplateDemo_A.cs" company="Lifeprojects.de">
//     Class: TemplateDemo_A
//     Copyright © Lifeprojects.de 2023
// </copyright>
//
// <author>Gerhard Ahrens - Lifeprojects.de</author>
// <email>developer@lifeprojects.de</email>
// <date>10.07.2023</date>
// <Template-Version>1.0</Template-Version>
//
// <summary>
// Class for
// </summary>
// <auto-generated>
//  Dieser Code wurde vom T4 Template-Generator generiert.
//
//  Änderungen an dieser Datei 'TemplateDemo_A.cs' können falsches Verhalten verursachen
//  und gehen verloren, wenn der Code erneut generiert wird. Es ist allerdings möglich zusätzliche 
//  Anpassunge in einer weiteren Klasse-Datei durch 'partial class TemplateDemo_A' durchzuführen.
// </auto-generated>
//-----------------------------------------------------------------------

namespace TemplateProject.Class
{
    using System;
    using System.Diagnostics;

    [DebuggerNonUserCode]
    [DebuggerStepThrough]
    public partial class TemplateDemo_A
    {
        public TemplateDemo_A()
        {
        }
    }
}